vip = game.Players.bob371
char = vip.Character
zipper = false

--pcall(function() char.Animate:Remove() end)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(4,0.4,4)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh",part)
mesh.Scale = Vector3.new(1.05,1.05,1.05)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-3,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(3.8,2,3.8)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
Instance.new("CylinderMesh").Parent = part
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-2,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(3.8,2,3.8)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1.1,1,1.1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(3.8,2,3.8)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.1,1,1.1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,-0.05) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(3.8,2,3.8)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1,3,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(3.8,2,3.8)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.1,3,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,-0.05) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(2,2,1.9)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,1.5,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1,2,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char["Left Arm"]
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1,1,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char["Left Arm"]
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,1.5,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1,2,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char["Right Arm"]
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(-0.1,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(1,1,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char["Right Arm"]
weld.Part1 = part
weld.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(-0.1,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Neon orange")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(2,2,6)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.7) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.5,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.6,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.7,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.8,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.9,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.85,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.75,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Reddish brown")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.65,2,7)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,1,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Cool yellow")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(1,1,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,2,-1.5) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("White")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(1,1,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0.5,2,-1.51) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("White")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(1,1,1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(-0.5,2,-1.51) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(0.1,1,0.1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(-0.2,2,-1.52) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("CylinderMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(0.1,1,0.1)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0.2,2,-1.52) * CFrame.fromEulerAnglesXYZ(math.pi/2,0,0)
if zipper == true then
part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("BlockMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(0.05,0.5,0.05)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(-0.1,0.9,-2.2) * CFrame.fromEulerAnglesXYZ(0,0,-0.4)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(2,2,2)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.Parent = part
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.1,2,2)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0,1.95,-0.03) * CFrame.fromEulerAnglesXYZ(0,0,0)

part = Instance.new("Part")
part.formFactor = "Plate"
part.Size = Vector3.new(1,1,1)
part.Anchored = false
part.Locked = true
part.CanCollide = true
part.BrickColor = BrickColor.new("Really black")
part.TopSurface = 0
part.BottomSurface = 0
part.Parent = char
mesh = Instance.new("BlockMesh")
mesh.Parent = part
mesh.Scale = Vector3.new(0.05,0.4,0.05)
weld = Instance.new("Weld")
weld.Parent = part
weld.Part0 = char.Torso
weld.Part1 = part
weld.C0 = CFrame.new(0.1,0.95,-2.2) * CFrame.fromEulerAnglesXYZ(0,0,0.4)
end
