vip = 'LocalPlayer'
if owner then vip = owner else vip = game.Players[vip] end
char = vip.Character
for i,v in pairs(char:GetChildren()) do 
	if v.className == "Part" then 
		v.Transparency = 1
		pcall(function() v:FindFirstChildWhichIsA("Decal"):Remove() end)
	elseif v:IsA("Accessory") then 
		pcall(function() 
			v:FindFirstChild("Handle").Transparency = 1 
		end) 
	end
end
script.Parent = char

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart1" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart2" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart3" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.8) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,2) 
knife.BrickColor = BrickColor.new("Bright orange") 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1.1,2,0.95) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,2.4,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1,1,1) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0.2,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.new("Bright orange")
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.01,1.5,1.01) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.7,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

----

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart1" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart2" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Yellow() 
knife.Parent = char 
knife.Name = "Bodypart3" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.1,1,1.1) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.8) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,2) 
knife.BrickColor = BrickColor.new("Bright orange") 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1.1,2,0.95) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.9,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,2.4,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1,1,1) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0.2,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.new("Bright orange")
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1.01,1.5,1.01) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.7,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1,1,1) 
w = Instance.new("Weld") 
w.Parent = char["Right Leg"] 
w.Part0 = char["Right Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart5" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1,1,1) 
w = Instance.new("Weld") 
w.Parent = char["Left Leg"] 
w.Part0 = char["Left Leg"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0) 

----

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(2,1.4,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1.2,1.8,1.9) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(2,1.4,1) 
knife.BrickColor = BrickColor.White() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.9,1.5,1.6) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0,-0.3) * CFrame.fromEulerAnglesXYZ(0,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1.5,1.5,1.5) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1.4,-0.1) * CFrame.fromEulerAnglesXYZ(0,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char -- helooooooooooooooooooooooooooooooooooooooooo
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.Transparency = 0
knife.CanCollide = false
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(1.5,2.5,1.3) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1.5,-0.2) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.5,0.75,0.5) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,2.2,-0.4) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Blue() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.25,0.5,0.65) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0.25,2.3,-0.33) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.5,0.75,0.5) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,2.2,-0.4) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Blue() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.25,0.5,0.65) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.25,2.3,-0.33) * CFrame.fromEulerAnglesXYZ(0.1,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Wedge"
kmesh.Scale = Vector3.new(1,1.8,2) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.3,0.85) * CFrame.fromEulerAnglesXYZ(1.7,0,0)
--[[
knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Wedge"
kmesh.Scale = Vector3.new(1,1,2.4) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0.3,0.9) * CFrame.fromEulerAnglesXYZ(1.5,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
kmesh = Instance.new("BlockMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(1,1,2.4) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0.4,0.5) * CFrame.fromEulerAnglesXYZ(1.5,0,0)]]

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Red()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,1.2,0.8) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1,0.7) * CFrame.fromEulerAnglesXYZ(-0.3,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Red()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,1.2,0.8) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,0.45,0.95) * CFrame.fromEulerAnglesXYZ(-0.2,0,0)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.Red()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,1.2,0.8) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,-0.15,1) * CFrame.fromEulerAnglesXYZ(-0.1,0,0)

----

Y = 0.2

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,1.2,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(0.6,1,0.6) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.4,0.4-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(0.7,1,0.7) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.32-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,-0.1)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.6) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.58,1-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.5-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.5-Y,0.1) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.4,0.4,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.5-Y,0.2) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.5-Y,-0.1) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.4,0.4,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Left Arm"] 
w.Part0 = char["Left Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(0.2,-0.2-Y,-0.2) * CFrame.fromEulerAnglesXYZ(0,0,-0.3)


----

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,1.2,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(0.6,1,0.6) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.4,0.4-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Plate"
knife.Size = Vector3.new(1,0.4,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("CylinderMesh") 
kmesh.Parent = knife 
kmesh.Scale = Vector3.new(0.7,1,0.7) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.32-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,0.1)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.6) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.58,1-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.5-Y,0) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.5-Y,0.1) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.4,0.4,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.5-Y,0.2) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.6,0.6,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.5-Y,-0.1) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.White()
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(0.4,0.4,0.2) 
w = Instance.new("Weld") 
w.Parent = char["Right Arm"] 
w.Part0 = char["Right Arm"]
w.Part1 = knife 
w.C0 = CFrame.new(-0.2,-0.2-Y,-0.2) * CFrame.fromEulerAnglesXYZ(0,0,0.3)

----

knife = Instance.new("Part") 
knife.formFactor = "Symmetric"
knife.Size = Vector3.new(1,1,1) 
knife.BrickColor = BrickColor.Green() 
knife.Parent = char 
knife.Name = "Bodypart4" 
knife.Locked, knife.TopSurface, knife.BottomSurface = true, 0, 0 
knife.CanCollide = false
knife.Transparency = 0
kmesh = Instance.new("SpecialMesh") 
kmesh.Parent = knife 
kmesh.MeshType = "Sphere"
kmesh.Scale = Vector3.new(2,2,2) 
w = Instance.new("Weld") 
w.Parent = char["Torso"] 
w.Part0 = char["Torso"]
w.Part1 = knife 
w.C0 = CFrame.new(0,1.2,-1) * CFrame.fromEulerAnglesXYZ(0,0,0)

for i,v in pairs(char:GetChildren()) do if v.className == "Part" then if v.BrickColor == BrickColor.Green() then v.BrickColor = BrickColor.new("Bright green") end end end