vip = 'LocalPlayer'
if owner then vip = owner else vip = game.Players[vip] end
character = vip.Character
for i,v in pairs(char:GetChildren()) do 
	if v.className == "Part" then 
		v.Transparency = 1
		pcall(function() v:FindFirstChildWhichIsA("Decal"):Remove() end)
	elseif v:IsA("Accessory") then 
		pcall(function() 
			v:FindFirstChild("Handle").Transparency = 1 
		end) 
	end
end

fireon = false
ironman = 0 -- 0 = yes | 1 = no

ironmodel = Instance.new("Model")
ironmodel.Name = "IronMan"
ironmodel.Parent = char

character.Head.Transparency = 1

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Really black")
partz.Transparency = 1
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = character["Left Arm"]
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Really black")
partz.Transparency = 1
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = character["Right Arm"]
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = ironman
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.25,-0.25) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Torso"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.5,1)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-0.5,-0.35) * CFrame.fromEulerAnglesXYZ(3.14/2,0,3.14)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(2.05,2.05,1.1)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Torso"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.5,1)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(-0.4,0.45,-0.35) * CFrame.fromEulerAnglesXYZ(3.14/2,3.14/2/2+0.35,3.14)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Torso"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.5,1)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.4,0.45,-0.35) * CFrame.fromEulerAnglesXYZ(3.14/2,-3.14/2/2-0.35,3.14)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.1,2.05,1.1)
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.1,2.05,1.1)
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.1,2.05,1.1)
w = Instance.new("Weld") 
w.Parent = character["Left Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.1,2.05,1.1)
w = Instance.new("Weld") 
w.Parent = character["Right Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.4,1.15)
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-0.4,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.4,1.15)
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-0.4,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.8,1.15)
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.4,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.8,1.15)
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.4,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.8,1.15)
w = Instance.new("Weld") 
w.Parent = character["Left Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.3,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.15,0.8,1.15)
w = Instance.new("Weld") 
w.Parent = character["Right Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.3,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Head"
mesh.Parent = partz
mesh.Scale = Vector3.new(1.3,1.3,1.3)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.5,0.25,0.5)
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.5,0.25,0.5)
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.5,0.25,0.5)
w = Instance.new("Weld") 
w.Parent = character["Left Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.5,0.25,0.5)
w = Instance.new("Weld") 
w.Parent = character["Right Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-1,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.8,0.6,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.2,0.2,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.3,0.35,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.2,0.2,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(-0.3,0.35,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.5
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Blue()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.25,0.1,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(-0.2,0.15,-0.425) * CFrame.fromEulerAnglesXYZ(0,0,-0.2)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.5
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Blue()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.25,0.1,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.2,0.15,-0.425) * CFrame.fromEulerAnglesXYZ(0,0,0.2)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
w = Instance.new("Weld") 
w.Parent = character["Right Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.8,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Shape = "Ball"
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
w = Instance.new("Weld") 
w.Parent = character["Left Arm"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,0.8,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("BlockMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.7,0.2,0.5)
w = Instance.new("Weld") 
w.Parent = character["Head"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0,-0.4,-0.4) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.25,0.5,0.5)
w = Instance.new("Weld") 
w.Parent = character["Left Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(-0.55,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Sphere"
mesh.Scale = Vector3.new(0.25,0.5,0.5)
w = Instance.new("Weld") 
w.Parent = character["Right Leg"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.55,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Head"
mesh.Scale = Vector3.new(0.8,2,0.8)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.4,0,0.75) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Reflectance = 0.1
partz.Shape = "Ball"
partz.Parent = ironmodel
partz.formFactor = "Symmetric"
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = ironman
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "Head"
mesh.Scale = Vector3.new(0.8,2,0.8)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(-0.4,0,0.75) * CFrame.fromEulerAnglesXYZ(0,0,0)

partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 0.1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Offset = Vector3.new(0,0.8,0)
mesh.Parent = partz
mesh.Scale = Vector3.new(1.85,0.3,1.85)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.3,-1.3,-1.4) * CFrame.fromEulerAnglesXYZ(-0.5,0,0.1)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 0.1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Offset = Vector3.new(0,-0.8,0)
mesh.Parent = partz
mesh.Scale = Vector3.new(1.85,0.3,1.85)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.3,-1.3,-1.4) * CFrame.fromEulerAnglesXYZ(-0.5,0,0.1)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.Material = "Ice"
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 0.1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(1.75,1.925,1.75)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.3,-1.3,-1.4) * CFrame.fromEulerAnglesXYZ(-0.5,0,0.1)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 0.1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Red()
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(1.7,1.8,1.7)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.3,-1.3,-1.4) * CFrame.fromEulerAnglesXYZ(-0.5,0,0.1)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.1,1.4,0.1)
w1 = Instance.new("Weld") 
w1.Parent = character["Right Arm"]
w1.Part0 = w1.Parent
w1.Part1 = partz
w1.C0 = CFrame.new(-0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.7,0,-0.5)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.new("Navy blue")
partz.Transparency = 0
mesh = Instance.new("CylinderMesh")
mesh.Parent = partz
mesh.Scale = Vector3.new(0.1,1.4,0.1)
w2 = Instance.new("Weld") 
w2.Parent = character["Left Arm"]
w2.Part0 = w2.Parent
w2.Part1 = partz
w2.C0 = CFrame.new(0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.7,0,0.5)
partz = Instance.new("Part")
partz.Name = "Torso"
partz.CanCollide = false
partz.Locked = true
partz.TopSurface = 0
partz.BottomSurface = 0
partz.Parent = character
partz.formFactor = "Symmetric"
partz.Reflectance = 0.1
partz.Size = Vector3.new(1,1,1)
partz.BrickColor = BrickColor.Yellow()
partz.Transparency = 0
mesh = Instance.new("SpecialMesh")
mesh.Parent = partz
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=3270017"
mesh.Scale = Vector3.new(1.65,1.65,2)
sound = Instance.new("Sound")
sound.Pitch = 0.5
sound.Volume = 0.05
sound.SoundId = "rbxasset://sounds\\paintball.wav"
sound.Parent = partz
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = partz
w.C0 = CFrame.new(0.21,-0.45,-1.875) * CFrame.fromEulerAnglesXYZ(3.14/2-0.5,0.1,0)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = character["Right Arm"]
w.C0 = CFrame.new(1.2,0.4,-0.7) * CFrame.fromEulerAnglesXYZ(3.14/2-0.4,0.1,-0.2)
w = Instance.new("Weld") 
w.Parent = character["Torso"]
w.Part0 = w.Parent
w.Part1 = character["Left Arm"]
w.C0 = CFrame.new(-0.8,0.4,-0.7) * CFrame.fromEulerAnglesXYZ(3.14/2-0.3,-0.1,0.3)

-- ring mesh: http://www.roblox.com/asset/?id=3270017

function Chatted(msg)
if string.sub(msg,1,5) == "tone/" then
num = string.sub(msg,6)
sound.Pitch = num
end
if string.sub(msg,1,7) == "volume/" then
num = string.sub(msg,8)
sound.Volume = num
end
if string.sub(msg,1,5) == "boom/" then
num = string.sub(msg,6)
ff = Instance.new("ForceField")
ff.Parent = char
wait(0.1)
e = Instance.new("Explosion")
e.Position = char.Torso.Position
e.BlastRadius = num
e.Parent = game.Workspace
wait(2)
ff:Remove()
end
end

vip.Chatted:connect(Chatted) 

while true do wait()
w1.C0 = CFrame.new(-0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.8,0,-0.5)
w2.C0 = CFrame.new(0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.7,0,0.5)
sound:Play()
wait()
w1.C0 = CFrame.new(-0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.7,0,-0.5)
w2.C0 = CFrame.new(0.3,-1,-0.3) * CFrame.fromEulerAnglesXYZ(-0.8,0,0.5)
sound:Play()
end