Name = "bob371"
vip = owner or game.Players.LocalPlayer or game.Players[Name]
char=  vip.Character
player = vip
Color=BrickColor.new("Grey")
Color2=BrickColor.new(Color3.new(0,0,0))
model=Instance.new("Model")
model.Name="Suit"
model.Parent=char
d=0
Debounce=true

for i,v in pairs(char.Head:GetChildren()) do if v.className == "Decal" then v.Texture = "http://www.roblox.com/asset/?id=9801981" end end

f = Instance.new("Decal")
f.Texture = "http://www.roblox.com/asset/?id=9801981"
f.Face = "Left"
f.Parent = char.Head

f = Instance.new("Decal")
f.Texture = "http://www.roblox.com/asset/?id=9801981"
f.Face = "Right"
f.Parent = char.Head

--[[function HatOn()
for i,v in pairs(script.Parent:GetChildren()) do if v.className == "Accessory" then v.Parent = char end end
end]]

function HatOff()
for i,v in pairs(char:GetChildren()) do if v.className == "Accessory" then 
	v.Parent = nil --script.Parent 
end end
end

HatOff()

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1,1.5,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.25,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1,1.5,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.25,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.55,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.75,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.55,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.75,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1


part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Really black")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.4,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.81,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Really black")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.4,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.81,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Bright red")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Wedge"
mesh.Scale = Vector3.new(0.95,1.4,0.7)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0.15,0.04,-0.05) * CFrame.fromEulerAnglesXYZ(0,3.14/2,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Bright red")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Wedge"
mesh.Scale = Vector3.new(0.95,1.4,0.7)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(-0.15,0.04,-0.05) * CFrame.fromEulerAnglesXYZ(0,-3.14/2,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.55,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.05,0.55,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Bright red")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1.1,0.4,1.1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Cool yellow")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(0.98,1,0.98)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Cool yellow")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(0.98,1,0.98)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Arm"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.5,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1,2,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Left Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(1,2,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Right Leg"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(2,2,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Cool yellow")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Head"
mesh.Scale = Vector3.new(1.25,1.25,1.25)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Head"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=16952952"
mesh.Scale = Vector3.new(1,1,1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Head"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.3,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Black")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "FileMesh"
mesh.MeshId = "http://www.roblox.com/asset/?id=16952952"
mesh.Scale = Vector3.new(0.95,0.95,0.95)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Head"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,0.3,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(2.05,0.55,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.8,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Bright red")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(2.1,0.3,1.1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0,-0.8,0) * CFrame.fromEulerAnglesXYZ(0,0,0)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Dark orange")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(2.5,0.5,1.05)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0.1,0.1,0) * CFrame.fromEulerAnglesXYZ(0,0,3.14/2/2)
weld.Parent.Transparency = 1

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("Mid gray")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(0.6,0.6,1.1)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0.1,0.1,0) * CFrame.fromEulerAnglesXYZ(0,0,3.14/2/2)

part = Instance.new("Part")
part.Anchored = false
part.CanCollide = false
part.Locked = true
part.formFactor = "Symmetric"
part.TopSurface = 0
part.BottomSurface = 0
part.BrickColor = BrickColor.new("White")
part.Size = Vector3.new(1,1,1)
part.Parent = char
mesh = Instance.new("SpecialMesh")
mesh.MeshType = "Brick"
mesh.Scale = Vector3.new(0.3,0.3,1.15)
mesh.Parent = part
weld = Instance.new("Weld") 
weld.Parent = char["Torso"]
weld.Part0 = weld.Parent
weld.Part1 = part
weld.C0 = CFrame.new(0.1,0.1,0) * CFrame.fromEulerAnglesXYZ(0,0,3.14/2/2)
weld.Parent.Transparency = 1
