--Generated by bob371

dataPosition = Vector3.new(1562,-296.6,-1708)

partData = {
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 305.5934143066406,dataPosition.Z + 1701.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389647",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 301.993408203125,dataPosition.Z + 1703.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389976",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 307.5934143066406,dataPosition.Z + 1712.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389523",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 305.19342041015625,dataPosition.Z + 1713.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389665",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 304.7934265136719,dataPosition.Z + 1709.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389691",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 300.7934265136719,dataPosition.Z + 1706.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390382",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 301.993408203125,dataPosition.Z + 1709.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389934",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 303.19342041015625,dataPosition.Z + 1712.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389828",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 303.19342041015625,dataPosition.Z + 1706.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389789",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 306.3934326171875,dataPosition.Z + 1706.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389584",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 299.5934143066406,dataPosition.Z + 1703.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390459",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 301.993408203125,dataPosition.Z + 1713.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389895",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 304.3934326171875,dataPosition.Z + 1703.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389759",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 307.993408203125,dataPosition.Z + 1703.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389494",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 298.3934326171875,dataPosition.Z + 1706.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390524",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 297.19342041015625,dataPosition.Z + 1703.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390662",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 299.5934143066406,dataPosition.Z + 1713.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390433",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 299.5934143066406,dataPosition.Z + 1709.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390447",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 300.7934265136719,dataPosition.Z + 1712.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390356",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 298.3934326171875,dataPosition.Z + 1712.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390484",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 297.19342041015625,dataPosition.Z + 1709.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390615",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 6),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 309.993408203125,dataPosition.Z + 1709.3126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389476",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 297.19342041015625,dataPosition.Z + 1713.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390584",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 311.5934143066406,dataPosition.Z + 1713.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389454",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 298.3934326171875,dataPosition.Z + 1701.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390542",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 300.7934265136719,dataPosition.Z + 1701.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6390405",},
	{name = "Smooth Block Model",size = Vector3.new(2, 1.2000000476837158, 3),brickColor = BrickColor.new("Bright red"),cframe = CFrame.new(dataPosition.X + -1577.4993896484375,dataPosition.Y + 303.19342041015625,dataPosition.Z + 1701.8126220703125),decalTexture = "http://www.roblox.com/asset/?id=6389847",},
}

part = function(name, size, brickColor, cframe, decalTexture, parent)
	local p = Instance.new("Part")
	p.Anchored = true
	p.Locked = true
	p.Size = size
	p.BrickColor = brickColor
	p.Name = name
	p.CFrame = cframe
	p.Parent = parent
	
	local d = Instance.new("Decal",p)
	d.Face = "Right"
	d.Texture = decalTexture
	
	return p
end

main = function()
	local model = Instance.new("Model",workspace)
	for i,v in pairs(partData) do
		part(v.name, v.size, v.brickColor, v.cframe, v.decalTexture, model)
	end
end

main()
